server:
  port: 4001 #端口号随意，默认是4000
  compress: true
  header: true

title: sunct的博客
subtitle: 我走路带风
description: sunc的博客
keywords: >-
  sunct,孙三苗,前端,博客,blog,js,jquery,javascript,html5,后端,开发者,程序猿,程序媛,极客,编程,代码,开源,IT网站,Developer,Programmer,Coder,Geek,html,css,css3,用户体验
author: sunct
language: zh-CN
timezone: ''
email: sunch1234@qq.com
url: 'https://sunct.github.io'
root: /
permalink_defaults: null
pretty_urls:
  trailing_index: true
  trailing_html: true
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: ':lang'
skip_render: null
new_post_name: ':title.md'
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
index_generator:
  path: ''
  per_page: 8
  order_by: '-date'
default_category: uncategorized
category_map: null
tag_map: null
archive: 1
category: 1
tag: 1
meta_generator: true
date_format: YYYY-MM-DD
time_format: 'HH:mm:ss'
use_date_for_updated: false
per_page: 5
pagination_dir: page
include: null
exclude: null
ignore: null
theme: icarus
deploy:
  type: ''
jsonContent:
  meta: false
  pages: false
  posts:
    title: true
    date: true
    path: true
    text: false
    raw: false
    content: false
    slug: false
    updated: false
    comments: false
    link: false
    permalink: false
    excerpt: false
    categories: false
    tags: true
word_count: true


# 首先找到并修改permalink的格式
permalink: posts/:abbrlink.html

# 然后再添加abbrlink的配置
# abbrlink config
abbrlink:
  alg: crc32  #support crc16(default) and crc32
  rep: hex    #support dec(default) and hex


plugins:
  gallery: true